version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run build

post_build:
  commands:
    - echo "Deploying to EC2..."
    - echo "$EC2_PRIVATE_KEY" > ec2_key.pem
    - chmod 400 ec2_key.pem
    - scp -o StrictHostKeyChecking=no -i ec2_key.pem -r ./build/* $EC2_USER@$EC2_HOST:/var/www/vhosts/frontend/build/
    - echo "Deployment complete!"
